tournament/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('tournaments.urls')),
]

tournaments/urls.py
'''
This is the python file for all the urls path in tournaments application
'''
from django.urls import path
from django.views.generic import TemplateView
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()

app_name = 'tournament'
urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('player', views.Index.player, name='player'),
    path('signup', views.Index.signup, name='signup'),
    path('tournaments/<int:tournament_id>/results', views.QuestionQuiz.results, name='results'),
    path('tournaments/<int:tournament_id>/start',
         views.QuestionQuiz.start_tournament, name='start_tournament'),
    path('tournaments/<int:tournament_id>/highscore',
         views.TournamentView.list_tournament_highscore, name='highscore'),
    path('tournaments/',
         views.TournamentView.list_all_tournament, name='list_all_tournament'),
    path('tournaments/ongoing',
         views.TournamentView.list_ongoing_tournament, name='list_ongoing_tournament'),
    path('tournaments/upcoming',
         views.TournamentView.list_upcoming_tournament, name='list_upcoming_tournament'),
    path('tournaments/past',
         views.TournamentView.list_past_tournament, name='list_past_tournament'),
    path('tournaments/<int:tournament_id>/questions',
         views.TournamentView.list_tournament_question, name='tournament_question'),
    path('tournaments_api/', views.TournamentList.as_view()),
    path('tournaments_api/<int:pk>/', views.TournamentDetail.as_view(), name='edit_tournament'),
    path('tournaments_api/create/', views.TournamentCreate.as_view(), name='create_tournament'),
]
urlpatterns = format_suffix_patterns(urlpatterns)
urlpatterns += router.urls

tournaments/models.py
'''
Python class that holds the models of the tournaments application
'''
from django.db import models
from django.contrib.auth.models import User

DIFFICULTY_CHOICE = [('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')]
CATEGORY_CHOICE = [('21', 'Sports'), ('22', 'Geography'), ('23', 'History'), ('25', 'Art')]

class Tournament(models.Model):
    '''
    tournament model
    '''
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=200, choices=CATEGORY_CHOICE)
    difficulty = models.CharField(max_length=50, choices=DIFFICULTY_CHOICE)
    start_date = models.DateField('start date')
    end_date = models.DateField('end date')

class Question(models.Model):
    '''
    question model
    '''
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    question = models.CharField(max_length=1000)
    correct_answer = models.CharField(max_length=500)
    choices1 = models.CharField(max_length=500)
    choices2 = models.CharField(max_length=500)
    choices3 = models.CharField(max_length=500)
    choices4 = models.CharField(max_length=500)

class TournamentPlayer(models.Model):
    '''
    tournament many to many relationship with player model
    '''
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    player = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    complete_date = models.DateField('complete_date', null=True)

tournaments/views.py
'''
View class for tournaments application
'''
import datetime
import random
import requests as rq
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Avg
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from rest_framework import mixins, generics
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAdminUser
from .models import Tournament, Question, TournamentPlayer
from .serializers import TournamentSerializer


NUMBER_OF_QUESTIONS = 10

class Index(TemplateView):
    '''
    Index template class, includes profile method and signup method
    '''
    template_name = "index.html"

    @login_required
    def player(request):
        '''
        Player function, after login, return user to players.html
        '''
        return render(request, 'players.html')

    def signup(request):
        '''
        Signup Method, validates user signup credentials and if there is validation error
        then it will return the user to the signup page with error messages. If validation passes
        then it will send the user to the profile page.
        '''
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                return redirect('/player')
        else:
            form = UserCreationForm()
        return render(request, 'registration/signup.html', {'form': form})

class TournamentView(TemplateView):
    '''
    Tournament Class view,
    process the created tournament and list them out according to their dates
    such as past, ongoing, upcoming tournaments.
    '''
    @login_required
    def list_all_tournament(request):
        '''
        List all the tournaments in the database
        '''
        tournaments = Tournament.objects.all()
        return render(request, 'tournaments_list.html', {'tournaments': tournaments})

    @login_required
    def list_tournament_question(request, tournament_id):
        '''
        List all the question of a tournament
        '''
        questions = Question.objects.all().filter(tournament_id=tournament_id)
        return render(request, 'questions_list.html', {'questions': questions})

    @login_required
    def list_tournament_highscore(request, tournament_id):
        '''
        List the score, participant and average sore for a tournament
        '''
        tour_play = TournamentPlayer.objects.filter(tournament_id=tournament_id).order_by('-score')
        total_taken = tour_play.count()
        average = tour_play.aggregate(Avg('score'))
        return render(request, 'highscore.html',
                      {'tour_play': tour_play, 'total_taken': total_taken, 'average':average})

    @login_required
    def list_ongoing_tournament(request):
        '''
        List all ongoing tournaments in the database
        '''
        tournaments_ongoing = True
        tournaments = Tournament.objects.filter(start_date__lte=datetime.date.today(),
                                                end_date__gte=datetime.date.today())
        return render(request, 'tournaments_list.html',
                      {'tournaments': tournaments, 'tournaments_ongoing':tournaments_ongoing})

    @login_required
    def list_upcoming_tournament(request):
        '''
        List all upcoming tournaments in the database
        '''
        tournaments = Tournament.objects.filter(start_date__gte=datetime.date.today())
        return render(request, 'tournaments_list.html', {'tournaments': tournaments})

    @login_required
    def list_past_tournament(request):
        '''
        List all past tournaments in the database
        '''
        tournaments_ongoing = False
        tournaments = Tournament.objects.filter(end_date__lte=datetime.date.today())
        return render(request, 'tournaments_list.html',
                      {'tournaments': tournaments, 'tournaments_ongoing':tournaments_ongoing})

class TournamentList(mixins.ListModelMixin,
                     generics.GenericAPIView):
    """
    List all tournaments, using mixin web api navigation
    """
    queryset = Tournament.objects.all()
    serializer_class = TournamentSerializer

    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAdminUser]

    def get(self, request, *args, **kwargs):
        '''
        mixins get method
        '''
        return self.list(request, *args, **kwargs)


class TournamentDetail(mixins.RetrieveModelMixin,
                       mixins.UpdateModelMixin,
                       mixins.DestroyModelMixin,
                       generics.GenericAPIView):
    """
    Retrieve, update or delete a tournament instance.
    """
    queryset = Tournament.objects.all()
    serializer_class = TournamentSerializer

    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAdminUser]

    def get(self, request, *args, **kwargs):
        '''
        mixins get method
        '''
        return self.retrieve(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        '''
        mixins put method
        '''
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        '''
        mixins delete method
        '''
        return self.destroy(request, *args, **kwargs)

class TournamentCreate(mixins.RetrieveModelMixin,
                       mixins.CreateModelMixin,
                       mixins.ListModelMixin,
                       generics.GenericAPIView):
    """
    Create a new tournament and adding questions to the tournament.
    """
    queryset = Tournament.objects.all()
    serializer_class = TournamentSerializer
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAdminUser]

    def get(self, request, *args, **kwargs):
        '''
        mixins get method
        '''
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        '''
        creating a tournament and get the question using api and store it together in the database
        '''
        tournament = self.create(request, *args, **kwargs)
        difficulty = tournament.data['difficulty']
        category = tournament.data['category']
        api_string = f'https://opentdb.com/api.php?amount=10&category={category}&difficulty={difficulty}&type=multiple'
        questions_json = rq.get(api_string).json() #requesting api from the link
        self.create_questions(questions_json, tournament)
        return tournament

    def create_questions(self, questions_json, tournament):
        '''Creating the 10 questions'''
        random_order = [1, 2, 3, 0] #declare array to randomize the choices' order
        for ques in range(NUMBER_OF_QUESTIONS):
            question = questions_json['results'][ques]['question']
            correct_answer = questions_json['results'][ques]['correct_answer']
            choices = [None, None, None, None] #declaring empty array
            #randoming the random_order array and filling in the choices
            random.shuffle(random_order)
            choices[random_order[0]] = questions_json['results'][ques]['incorrect_answers'][0]
            choices[random_order[1]] = questions_json['results'][ques]['incorrect_answers'][1]
            choices[random_order[2]] = questions_json['results'][ques]['incorrect_answers'][2]
            choices[random_order[3]] = questions_json['results'][ques]['correct_answer']
            Question.objects.create(tournament=Tournament.objects.get(id=tournament.data['id']),
                                    question=question,
                                    correct_answer=correct_answer,
                                    choices1=choices[0],
                                    choices2=choices[1],
                                    choices3=choices[2],
                                    choices4=choices[3])

class QuestionQuiz(TemplateView):
    '''
    Class view for 10 question quiz
    '''
    @login_required
    def start_tournament(request, tournament_id):
        '''
        Starting the tournament, this method check if the user
        has taken the tournament or not, if not it will get the
        tournament id and user id and create a database entry
        '''
        if not TournamentPlayer.objects.filter(tournament_id=tournament_id,
                                               player_id=request.user.id).exists():
            TournamentPlayer.objects.create(tournament=Tournament.objects.get(id=tournament_id),
                                            player=request.user)
            questions = Question.objects.all().filter(tournament_id=tournament_id)
            return render(request, 'question.html',
                          {'questions': questions, 'tournament_id':tournament_id})
        else:
            taken = 'You have taken the tournament already'
            return render(request, 'players.html', {'taken':taken})

    @login_required
    def results(request, tournament_id):
        '''
        Processing the number of correct answer the user has given
        and give a result
        '''
        questions = Question.objects.all().filter(tournament_id=tournament_id)
        #getting the question id so that it can retrieve the value(user answers) from the form
        question_ids = [str(questions[id].id)for id in range(len(questions))]

tournaments/templates/base.html
<html>
  {# Base template #}
    {% block head %}
        <head>      
            <title>{% block title %}OpenTDB Tournament{% endblock %}</title>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            {% load static %}
            <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
        </head>
    {% endblock head%}
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
              <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'tournament:index' %}">OPENTDB</a></li>
                {# Navigation bar#}
                {% if user.is_authenticated %}
                  <li><a href="{% url 'tournament:list_all_tournament' %}">View Tournaments</a></li>
                  <li><a href="{% url 'tournament:list_ongoing_tournament' %}">View Ongoing Tournaments</a></li>
                  <li><a href="{% url 'tournament:list_upcoming_tournament' %}">View Upcoming Tournaments</a></li>
                  <li><a href="{% url 'tournament:list_past_tournament' %}">View Past Tournaments</a></li>
                  {% if user.is_superuser %}
                    <li><a  href="{% url 'tournament:create_tournament' %}">Create Tournament</a></li>
                  {% endif %}
                  <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                  <li><a class="navbar-link" href="{% url 'login' %}">Login</a></li>
                  <li><a class="navbar-link" href="{% url 'tournament:signup' %}">Sign Up</a></li>
                {% endif %}
              </ul>
            </div>
          </nav>
        <div class="container">
            <main>
                {% block content %}
                {% endblock content%}
            </main>
        </div> 
    </body>
</html>

tournaments/templates/highscore.html
{% extends 'base.html' %}
{# highscore page #}
{% block title %}Home{% endblock %}

{% block content %}
    Average Score: {{average.score__avg}}
    Total Taken: {{total_taken}}
    {% if tour_play %}
    <table class="table">
        <th>
            Name
        </th>
        <th>
            Complete Date
        </th>
        <th>
            Score
        </th>
    {% for tp in tour_play%}
    <tr>
        <td>
            {{ tp.player }}
        </td>
        <td>
            {{ tp.complete_date }}
        </td>
        <td>
            {{ tp.score}}
        </td>
    </tr>
    {% endfor %}
    </table>
    {% else %}
        No score found
    {% endif %}
{% endblock %}

tournaments/templates/index.html
{% extends 'base.html' %}
{# index page #}
{% block content %}   
    <p>This is an opentdb tournament</p>
{% endblock content%}

tournaments/templates/players.html
{% extends 'base.html' %}
{# Players profile page #}
{% block title %}Home{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hi {{ user.username }}!
  {% endif %}
  {{ taken }}
{% endblock %}

tournaments/templates/question.html
{% extends 'base.html' %}
{# Question page that shows the questions for a tournament #}
{% block content %}   
{% if user.is_authenticated %}
<table class="table">
    
        <th>
            Question
        </th>
        <th>
            Choice 1
        </th>
        <th>
            Choice 2
        </th>
        <th>
            Choice 3
        </th>
        <th>
            Choice 4
        </th>
<form action="{% url 'tournament:results' tournament_id=tournament_id%}" method="post">
    {% csrf_token %}
    {% autoescape off %}
    {% for question in questions%}   
    <tr>
        <td>  
            {{question.question}}
        </td> 
        <td>  
            <input type='radio' id='option1' name='{{question.id}}' value='{{question.choices1}}'>
            {{question.choices1}}
        </td> 
        <td>  
            <input type='radio' id='option2' name='{{question.id}}' value='{{question.choices2}}'>
            {{question.choices2}}
        </td> 
        <td>  
            <input type='radio' id='option3' name='{{question.id}}' value='{{question.choices3}}'>
            {{question.choices3}}
        </td> 
        <td>  
            <input type='radio' id='option4' name='{{question.id}}' value='{{question.choices4}}'>
            {{question.choices4}}
        </td> 
    </tr>
    {% endfor %}  
    {% endautoescape  %}
    <input type='submit' value='Click To Submit'>
    </form>
</table>
{% else %}
<p>
    You do not have permission to view the questions
</p>
{% endif %}
{% endblock content%}

tournaments/templates/questions_list.html
{% extends 'base.html' %}
{# Questions quiz page#}
{% block content %}   
{% if user.is_superuser %}
<table class="table">
    
        <th>
            Question
        </th>
        <th>
            Correct answer
        </th>
        <th>
            Choices 1
        </th>
        <th>
            Choices 2
        </th>
        <th>
            Choices 3
        </th>
        <th>
            Choices 4
        </th>
    
    {% for question in questions%}
    <tr>
        <td>  
            {{question.question}}
        </td> 
        <td>  
            {{question.correct_answer}}
        </td> 
        <td>  
            {{question.choices1}}
        </td> 
        <td>  
            {{question.choices2}}
        </td> 
        <td>  
            {{question.choices3}}
        </td> 
        <td>  
            {{question.choices4}}
        </td> 
    </tr>
    {% endfor %}  
</table>
{% else %}
<p>
    You do not have permission to view the questions
</p>
{% endif %}
{% endblock content%}

tournaments/templates/results.html
{% extends 'base.html' %}
{# Rusults page that is used to count the final score and give feedback to the user on the questions' answers#}
{% block content %} 
<h1>Final Score: {{correct_count}}/10</h1>
<div class="container">
    <div class="col-sm-8">
    <div class="row">
        <div class="col-sm-4">
            <h1>Incorrect Questions</h1>
        </div>
        <div class="col-sm-4" >
            <h1>Correct Answer</h1>
        </div>
    </div>  
    {% autoescape off %}
        {% for ques in incorrect_match_question%}  
            <div class="row" >
                <div class="col-sm-4" >
                    {{ques.question}}
                </div>
                <div class="col-sm-4" >
                    {{ques.correct_answer}}
                </div>
            </div>  
            <br>  
        {% endfor %}       
    </div>
    <div class="col-sm-4" >
        <h1>Your Answer</h1>
        {% for ans in user_incorrect_answer%} 
            <div class="row" >
                {{ans}}
            </div>
            <br>
        {% endfor %}
    </div>  
    {% endautoescape %}
</div>

{% endblock content%}

tournaments/templates/tournaments_list.html
{% extends 'base.html' %}
{# Tournament page which is used by past,ongoing,upcoming views#}
{% block content %}   
<table class="table">
    
        <th>
            Name
        </th>
        <th>
            Difficulty
        </th>
        <th>
            Category
        </th>
        <th>
            Start date
        </th>
        <th>
            End date
        </th>
        {% if user.is_superuser %}
        <th>
            Modify
        </th>
        <th>
            View questions
        </th>
        {% endif %}
        {% if tournaments_ongoing is not None%}
            {% if tournaments_ongoing %}
                <th>
                    Take Part in Tournament
                </th>
            {% else %}
                <th>
                    View High Score
                </th>
            {% endif %}               
        {% endif %}  
        
    {% for tournament in tournaments%}
    <tr>
        <td>  
            {{tournament.name}}
        </td> 
        <td>  
            {{tournament.get_difficulty_display}}
        </td> 
        <td>  
            {{tournament.get_category_display}}
        </td> 
        <td>  
            {{tournament.start_date}}
        </td> 
        <td>  
            {{tournament.end_date}}
        </td> 
        {% if user.is_superuser %}
        <td>  
            <a class="btn btn-primary" href="{% url 'tournament:edit_tournament' pk=tournament.id%}">Modify Tournaments</a></li>
        </td>
        <td>  
            <a class="btn btn-primary" href="{% url 'tournament:tournament_question' tournament_id=tournament.id%}">View Questions</a></li>
        </td>
        {% endif %}
        {% if tournaments_ongoing is not None%}
            {% if tournaments_ongoing %}
                <th>
                    <a class="btn btn-primary" href="{% url 'tournament:start_tournament' tournament_id=tournament.id%}">Take part in Tournament</a></li>
                </th>
            {% endif %}  
                <th>
                    <a class="btn btn-primary" href="{% url 'tournament:highscore' tournament_id=tournament.id%}">View HighScore</a></li>
                </th>
                         
        {% endif %} 
    </tr>
    {% endfor %}  
</table>
{% endblock content%}